version: '3.8'

services:
  backend:
    build:
      context: ./backkend
      dockerfile: Dockerfile
    container_name: ats-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backkend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ats-frontend
    ports:
      - "5173:80"
    command: nginx -g 'daemon off;'
    depends_on:
      - backend

networks:
  default:
    name: ats-network
